### ISSUE TITLE
Agregar validaciones a los atributos de las entidades

### ISSUE THREAD

**Issue by ghost** [Martajua/TrabajoFinalVisual2023#11]
# Paquete

- [x] `ar.edu.unju.fi.entity`

# Entidades

- [x] + `Usuario.java`
- [x] + `IndiceMasaCorporal.java`
- [x] + `Receta.java`
- [x] + `Ingrediente.java`
- [x] + `Testimonio.java`

# Validaciones
Por ejemplo: `@Size`, `@Min`, `@Max`, `@NotBlank`, `@Email`, `@NotEmpty`, `@NotNull`, `@Past`, `@Future`, `@Pattern`

- [x]  Agregar anotaciones para la validación de los atributos de las entidades

**Comment by JorgeArielS93** [comment]
tarea en progreso

**Comment by JorgeArielS93** [comment]
tarea completada
