### ISSUE TITLE
Capa controller 

### ISSUE THREAD

**Issue by Martajua** [Martajua/TrabajoFinalVisual2023#5]
Crear un nuevo paquete dentro del proyecto denominado controller, que representará a la capa controladora, en este paquete se agruparán todas las clases java de tipo @Controller.
Carpeta ar.edu.unju.fi.controller

- IndexController.java
- RegistroController.java
- ServicioController.java
- RecetaController.java
- TestimonioController.java
- ContactoController.java
- GestionContoller.java

**Comment by JorgeArielS93** [comment]
Se crearon un primer avance de todas las clases controladoras.


![Image](https://github.com/Martajua/TrabajoFinalVisual2023/assets/70386725/666944cb-45c2-455c-a641-2a728ed7ae9c)
