### ISSUE TITLE
Creación de la carpeta templates-layouts

### ISSUE THREAD

**Issue by Martajua** [Martajua/TrabajoFinalVisual2023#6]
#Creación de la carpeta templates
Dentro de la carpeta templates cree los siguientes archivos html para la plataforma web de salud y bienestar. 

- inicio.html
- registros.html
- servicios.html
- recetas.html
- testimonios.html
- contacto.html
- gestionDatos.html

#Creación de la carpeta layouts
Cree una carpeta dentro de templates, denominada layouts. Aquí se encontrarán las regiones en común que tengan las paginas html, estas serán:

- header.html
- nav.html
- footer.hmtl

**Comment by Martajua** [comment]
Editando el contenido del archivos html

**Comment by JorgeArielS93** [comment]
header.html, nav.htmly footer.html realizados y configurados

**Comment by JorgeArielS93** [comment]
se completo esta tarea
