### ISSUE TITLE
Incorparación bootstrap-css

### ISSUE THREAD

**Issue by Martajua** [Martajua/TrabajoFinalVisual2023#7]
#Incorporar el uso de bootstrap para organizar todo el contenido de los archivos html. El sitio se debe adaptar (ser responsive) para los diferentes tamaños de dispositivos.

- Containers
- Filas
- Columnas
- Alineación
- Formularios y componentes necesarios en las páginas del proyecto.

#Dentro de la carpeta static, cree una nueva carpeta con el nombre css, en esta carpeta agregar un archivo denominado estilos.css

- estilos.css

**Comment by JorgeArielS93** [comment]
se completo esta tarea
