### ISSUE TITLE
Crear capa entity y sus correspondientes clases

### ISSUE THREAD

**Issue by ghost** [Martajua/TrabajoFinalVisual2023#9]
# Paquete

- [x] + `ar.edu.unju.fi.entity`

# Entidades

- [x] + `Usuario.java`
- [x] + `IndiceMasaCorporal.java`
- [x] + `Receta.java`
- [x] + `Ingrediente.java`
- [x] + `Testimonio.java`

**Comment by JorgeArielS93** [comment]
tarea completada
